language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Tuples"); Pkg.test("Tuples"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("Tuples")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
